name: CI/CD

on: push

jobs:

  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: pip install black flake8

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          continue_on_error: false
          black: true
          flake8: true
          flake8_args: "--ignore E1,E2,E3,E5,W1,W2,W3,W5" # black already handles formatting, this prevents conflicts
  define-environment:
    name: Set ✨ environment ✨ based on the branch 🌳
    runs-on: ubuntu-latest
    needs: run-linters
    steps:
      - name: Set the environment
        id: define_environment
        run: |
          if [ "${{ github.ref_name }}" == "hec" ]; then
            echo "env_names=[\"production\", \"hec_deployment\"]" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref_name }}" == "dev" ]; then
            echo "env_names=[\"development\"]" >> $GITHUB_OUTPUT
          else
            echo "No environment associated with ${GITHUB_REF##*/} branch"
          fi
      - name: Print the environment
        if: ${{ steps.define_environment.outputs.env_name }}
        run: echo "The environment is ${{ steps.define_environment.outputs.env_name }}"

    outputs:
      env_names: ${{ steps.define_environment.outputs.env_names }}

  deploy-blockchain:
    needs: define-environment
    name: Deploy to ✈️ ${{ matrix.value }} 🛩️
    if: ${{ needs.define-environment.outputs.env_names }}
    uses: "./.github/workflows/deploy.yml"
    strategy:
      matrix:
        value: ${{fromJson(needs.define-environment.outputs.env_names)}}
    with:
      environment: ${{ matrix.value }}
      env-file: ".envs"
      role-session-name: "openscience-blockchain-github-development-deployment"
      aws-region: "us-east-1"

    secrets: inherit



