name: Deploy

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      stage:
        type: string
        required: true
      env-file:
        type: string
        required: true
      environment:
        type: string
        required: true
      aws-region:
        type: string
        required: true
      role-session-name:
        required: false
        type: string
        default: github-actions-deployment
    secrets:
      DEPLOYMENT_ROLE_ARN:
        required: true
      MCP_ROLE:
        required: true
      ROLE_ARN:
        required: true





jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      STAGE: ${{ inputs.stage }}
      AWS_REGION: ${{ inputs.aws-region }}
      ROLE_ARN: ${{ secrets.ROLE_ARN }}



    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: "true"
          submodules: "recursive"
          token: ${{ secrets.READ_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN }}
          role-session-name: ${{ inputs.role-session-name }}
          aws-region: ${{ inputs.aws-region }}
      - name: Get relevant environment configuration from aws secrets
        shell: bash
        env:
          SECRET_SSM_NAME: ${{ vars.SECRET_SSM_NAME }}
          AWS_DEFAULT_REGION: ${{ inputs.aws-region }}
        run: |
          aws secretsmanager get-secret-value --secret-id $SECRET_SSM_NAME --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' > .s_env


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.3

      - name: Deploy
        run: |
          cat ${{ inputs.env-file }} >> .s_env
          cat .s_env
          bash deploy.sh .s_env <<< init
          bash deploy.sh .s_env <<< plan
