name: Deploy

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      stage:
        type: string
        required: true
      env-file:
        type: string
        required: true
      environment:
        type: string
        required: true
      aws-region:
        type: string
        required: true
      role-session-name:
        required: false
        type: string
        default: github-actions-deployment
    secrets:
      DEPLOYMENT_ROLE_ARN:
        required: true





jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      STAGE: ${{ inputs.stage }}
      AWS_REGION: ${{ inputs.aws-region }}
      PREFIX: ${{ vars.PREFIX }}
      MEMBER_ADMIN_USERNAME: ${{ secrets.MEMBER_ADMIN_USERNAME }}
      MEMBER_ADMIN_PASSWORD: ${{ secrets.MEMBER_ADMIN_PASSWORD }}
      STATE_BUCKET_NAME: ${{ vars.STATE_BUCKET_NAME }}
      STORAGE_BUCKET: ${{ vars.STORAGE_BUCKET }}
      APP_CLIENT_ID: ${{ secrets.APP_CLIENT_ID }}
      USER_POOL_ID: ${{ secrets.USER_POOL_ID }}


    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: "true"
          submodules: "recursive"
          token: ${{ secrets.READ_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN }}
          role-session-name: ${{ inputs.role-session-name }}
          aws-region: ${{ inputs.aws-region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.3

      - name: Deploy
        run: |
          cat terraform.tf
          bash deploy.sh ${{ inputs.env-file }} <<< init
          bash deploy.sh ${{ inputs.env-file }} <<< plan
         

