name: Deploy

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      stage:
        type: string
        required: true
      env-file:
        type: string
        required: true
      environment:
        type: string
        required: true
      aws-region:
        type: string
        required: true
      role-session-name:
        required: false
        type: string
        default: github-actions-deployment
    secrets:
      VPC_ID:
        required: true
      SUBNET_ID:
        required: true
      MEMBER_ADMIN_PASSWORD:
        required: true





jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      AWS_REGION: us-east-1
      VPC_ID: ${{ secrets.VPC_ID }}
      SUBNET_ID: ${{ secrets.SUBNET_ID }}
      MEMBER_ADMIN_USERNAME: ${{ vars.MEMBER_ADMIN_USERNAME }}
      MEMBER_ADMIN_PASSWORD: ${{ secrets.MEMBER_ADMIN_PASSWORD }}
      STATE_BUCKET_NAME: ${{ vars.STATE_BUCKET_NAME }}
      TF_VAR_storage_bucket: ${{ vars.STORAGE_BUCKET }}


    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: "true"
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN }}
          role-session-name: ${{ inputs.role-session-name }}
          aws-region: ${{ inputs.aws-region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.3

      - name: Deploy
        run: |
          ./scripts/deploy.sh ${{ inputs.env-file }} <<< init
          ./scripts/deploy.sh ${{ inputs.env-file }} <<< plan

